# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  devicename: "airgradient-one"
  friendly_devicename: "Airgradient One"
  ag_esphome_config_version: 1.0.0
  add_mac_suffix: "true"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired

ota:  # Add password as desired

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap: {}

packages:
  board: github://enjoylifenow/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  pm_2.5: github://enjoylifenow/airgradient_esphome/packages/sensor_pms5003.yaml@v0.0.1-alpha
  co2: github://enjoylifenow/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://enjoylifenow/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc: github://enjoylifenow/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://enjoylifenow/airgradient_esphome/packages/display_sh1106_multi_page.yaml@v0.0.1-alpha
  led: github://enjoylifenow/airgradient_esphome/packages/led.yaml@v0.0.1-alpha
  led_co2: github://enjoylifenow/airgradient_esphome/packages/led_co2.yaml@v0.0.1-alpha
  led_pm25: github://enjoylifenow/airgradient_esphome/packages/led_pm25.yaml@v0.0.2-alpha
  airgradient_api: github://enjoylifenow/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://enjoylifenow/airgradient_esphome/packages/watchdog.yaml
  config_button: github://enjoylifenow/airgradient_esphome/packages/config_button.yaml
  wifi: github://enjoylifenow/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://enjoylifenow/airgradient_esphome/packages/sensor_uptime.yaml
  safe_mode: github://enjoylifenow/airgradient_esphome/packages/switch_safe_mode.yaml

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
